{% set name = "venn" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/venn-{{ version }}.tar.gz
  sha256: 1a30f9bc0a28806a6214bba3623a04fea498119c19e22a9d293b31e561aa2091

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - python >={{ python_min }}

test:
  imports:
    - venn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/venn/
  summary: Venn diagrams for 2, 3, 4, 5, 6 sets
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
